---
permalink: reference-volume-shadow-copy-service-error-an-internal-inconsistency-was-detected.html 
sidebar: sidebar 
keywords: volume, shadow, copy, service, error, internal, inconsistency, detect 
summary: 'Fehler beim Volume Shadow Copy Service: Es wurde eine interne Inkonsistenz erkannt.' 
---
= Fehler beim Volume Shadow Copy Service: Es wurde eine interne Inkonsistenz erkannt
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Nachricht*
+
`Volume Shadow Copy Service error: An internal inconsistency was detected in trying to contact shadow copy service writers. Please check to see that the Event Service and Volume Shadow Copy Service are operating properly.`

* *Beschreibung*
+
Wenn Sie eine Sicherung einer virtuellen Maschine durchführen, die Windows Server 2003 verwendet, schlägt sie aufgrund eines Wiederholungsfehlers wiederholt fehl.

* *Korrekturmaßnahmen*
+
Überprüfen Sie das Ereignisprotokoll der Windows-Anwendung innerhalb der virtuellen Maschine auf VSS-Fehler.



*Verwandte Informationen*

http://support.microsoft.com/kb/940184["Microsoft Support Artikel 940184: Fehlermeldung, wenn Sie den Befehl "vssadmin list Writer" auf einem Windows Server 2003-basierten Computer ausführen: "Fehler: 0x8000FFFF""]
