---
permalink: reference-vss-returns-errors-against-microsoft-iscsi-target-vss-hardware-provider-during-nas-backup.html 
sidebar: sidebar 
keywords: vss, return, error, micorsoft, iscsi, target, hardware, provider, nas, backup 
summary: VSS gibt während der NAS-Sicherung Fehler gegen Microsoft iSCSI Target VSS Hardware Provider aus. 
---
= VSS gibt während der NAS-Sicherung Fehler gegen Microsoft iSCSI Target VSS Hardware Provider aus
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Ausgabe*
+
Während eines NAS-Backups können folgende Fehler auftreten:

+
`Vss Requestor - Backup Components failed. Failed to add volume [example] to snapshot set. The shadow copy provider had an unexpected error while trying to process the specified operation.``

+
`Volume Shadow Copy Service error: Error creating the Shadow Copy Provider COM class with CLSID [example]. Access is denied.`

* *Ursache*
+
Diese Fehler treten bei einem applikationskonsistenten NAS-Backup auf. NAS Backup schlägt nicht fehl, aber VSS protokolliert einige Fehler im Zusammenhang mit Microsoft iSCSI Target VSS Hardware Provider.

* *Korrekturmaßnahmen*
+
Die Sicherung ist nicht fehlgeschlagen. Sie können diese Fehler ohne Bedenken ignorieren.


