---
permalink: reference-web-service-client-channel-was-unable-to-connect-to-the-configurationmanagementservice-instance-on-machine-smhv51-81clus.html 
sidebar: sidebar 
keywords: web, service, client, channel, unable, conntect, configurationmanagementservice, instance, machine, smhv51_81clus 
summary: Web Service Client Kanal konnte keine Verbindung zur KonfigurationManagementService-Instanz auf Maschine smhv51_81clus herstellen. 
---
= Web Service Client Kanal konnte keine Verbindung zur KonfigurationManagementService-Instanz auf Maschine smhv51_81clus herstellen
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* *Nachricht*
+
`Web Service Client channel was unable to connect to the ConfigurationManagementService instance on machine smhv51_81clus.`

+
`There was no endpoint listening at net.tcp://smhv51_81clus/SnapManager/HyperV/ConfigMgmtService/v_10 that could accept the message. This is often caused by an incorrect address or SOAP action. See InnerException, if present, for more details.`

* *Beschreibung*
+
Wenn Sie Konfigurationsinformationen exportieren, werden die Einstellungen des lokalen Webservice-Ports der verwalteten Hosts in der exportierten Konfigurationsdatei gespeichert. Wenn Sie SnapManager für Hyper-V später mithilfe eines anderen Webservice-Ports neu installieren und die früheren Konfigurationsinformationen importieren müssen, treten Verbindungsprobleme auf.

* *Korrekturmaßnahmen*
+
Um dieses Problem zu vermeiden, verwenden Sie bei der Neuinstallation von SnapManager für Hyper-V dieselben Einstellungen für den Webservice-Port, die in der exportierten Konfigurationsdatei enthalten sind


