---
permalink: task-uninstall-snapmanager-for-hyper-v.html 
sidebar: sidebar 
keywords: snapmanager, hyper-v, windows, server, control, panel, uninstall, application, operating, system, remote, host, protection 
summary: Sie können SnapManager für Hyper-V über den Windows-Server deinstallieren, indem Sie die Systemsteuerung unter Ihrem Betriebssystem deinstallieren. 
---
= Deinstallieren Sie SnapManager for Hyper-V
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Sie können SnapManager für Hyper-V über den Windows-Server deinstallieren, indem Sie die Systemsteuerung unter Ihrem Betriebssystem deinstallieren. Sie können SnapManager für Hyper-V per Fernzugriff auf Standalone- und Cluster-Knoten oder Hosts deinstallieren. Verwenden Sie dazu den Assistenten für die Remote-Hostinstallation im Fenster Aktionen im Fenster Schutz.

.Über diese Aufgabe
Durch die Deinstallation von SnapManager for Hyper-V werden alle Datensätze und Richtlinien gelöscht. Sie können diese Informationen nicht wiederherstellen, nachdem die Deinstallation abgeschlossen ist. Wenn Sie Ihre Datensätze speichern und Informationen zur Hostkonfiguration speichern möchten, können Sie sie exportieren, bevor Sie sie deinstallieren.

.Schritte
. Navigieren Sie auf dem Windows-Server, auf dem Sie SnapManager für Hyper-V installiert haben, zur Systemsteuerung und wählen Sie Menü:Systemsteuerung[Programme > Programme und Funktionen].
. Blättern Sie durch die Liste der installierten Programme, um SnapManager for Hyper-V zu finden
. Klicken Sie auf den Namen des Programms und dann auf *Deinstallieren*.
. Wenn Sie zur Bestätigung der Deinstallation aufgefordert werden, klicken Sie auf *Ja*.


*Verwandte Informationen*

xref:task-import-or-export-host-and-dataset-configuration-information.adoc[Importieren oder Exportieren von Konfigurationsinformationen für Hosts und Datensätze]
